/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.panel;

import java.awt.HeadlessException;
import java.awt.Image;
import java.io.File;
import java.io.FileNotFoundException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import modelo.Apoderado;
import modelo.ApoderadoDAO;
import modelo.CertificadosDAO;

/**
 *
 * @author aleja
 */
public class pnlApoderado extends javax.swing.JPanel {

    /**
     * Creates new form pnlApoderado
     */
    public pnlApoderado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtnomimagen = new javax.swing.JTextField();
        btnseleccionar = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        txAfp = new javax.swing.JTextField();
        txtAFP2 = new javax.swing.JTextField();
        btnRegistrar = new javax.swing.JButton();
        btnSelectAfp = new javax.swing.JButton();
        btnSelectAfp2 = new javax.swing.JButton();
        lblfoto = new javax.swing.JLabel();
        panel_apoderado = new javax.swing.JPanel();
        jlContrasena = new javax.swing.JLabel();
        txtContra = new javax.swing.JTextField();
        jlDireccion = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        jlemail = new javax.swing.JLabel();
        txtemail = new javax.swing.JTextField();
        jlCelular = new javax.swing.JLabel();
        TxtComuna = new javax.swing.JTextField();
        jlNumeroDireccion = new javax.swing.JLabel();
        TxtN_direccion = new javax.swing.JTextField();
        jlCiudad = new javax.swing.JLabel();
        txtp_nombre = new javax.swing.JTextField();
        TxtCiudad = new javax.swing.JTextField();
        jlNombre = new javax.swing.JLabel();
        jlComuna = new javax.swing.JLabel();
        jlApellido = new javax.swing.JLabel();
        txtCelular = new javax.swing.JTextField();
        txtp_apellido = new javax.swing.JTextField();
        txts_apellido = new javax.swing.JTextField();
        jlRun = new javax.swing.JLabel();
        txtRun = new javax.swing.JTextField();
        btnBuscarRun = new javax.swing.JButton();
        TxtDvrun = new javax.swing.JTextField();
        btnLimpiar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Certificados"));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(0, 0, 255));
        jLabel1.setText("Finiquitos");

        txtnomimagen.setBackground(new java.awt.Color(204, 204, 255));
        txtnomimagen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnomimagenActionPerformed(evt);
            }
        });

        btnseleccionar.setText("Seleccionar");
        btnseleccionar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnseleccionarActionPerformed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 0, 255));
        jLabel2.setText("AFP2 (Opcional)");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(0, 0, 255));
        jLabel4.setText("AFP");

        txAfp.setBackground(new java.awt.Color(204, 204, 255));

        txtAFP2.setBackground(new java.awt.Color(204, 204, 255));

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        btnSelectAfp.setText("Seleccionar");
        btnSelectAfp.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectAfpActionPerformed(evt);
            }
        });

        btnSelectAfp2.setText("Seleccionar");
        btnSelectAfp2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSelectAfp2ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel4))
                .addGap(26, 26, 26)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(txtnomimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(btnseleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtAFP2, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txAfp, javax.swing.GroupLayout.PREFERRED_SIZE, 167, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSelectAfp2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 201, Short.MAX_VALUE)
                                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btnSelectAfp, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnseleccionar, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtnomimagen, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txAfp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectAfp, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtAFP2, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnSelectAfp2, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(20, Short.MAX_VALUE))
        );

        panel_apoderado.setBackground(new java.awt.Color(255, 255, 255));
        panel_apoderado.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Apoderado"));

        jlContrasena.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jlContrasena.setForeground(new java.awt.Color(0, 0, 255));
        jlContrasena.setText("Contraseña");

        txtContra.setBackground(new java.awt.Color(204, 204, 255));

        jlDireccion.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jlDireccion.setForeground(new java.awt.Color(0, 0, 255));
        jlDireccion.setText("Direccion");

        txtDireccion.setBackground(new java.awt.Color(204, 204, 255));
        txtDireccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtDireccionActionPerformed(evt);
            }
        });
        txtDireccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtDireccionKeyTyped(evt);
            }
        });

        jlemail.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jlemail.setForeground(new java.awt.Color(0, 0, 255));
        jlemail.setText("E-Mail");

        txtemail.setBackground(new java.awt.Color(204, 204, 255));

        jlCelular.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jlCelular.setForeground(new java.awt.Color(0, 0, 255));
        jlCelular.setText("Celular");

        TxtComuna.setBackground(new java.awt.Color(204, 204, 255));
        TxtComuna.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtComunaActionPerformed(evt);
            }
        });
        TxtComuna.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtComunaKeyTyped(evt);
            }
        });

        jlNumeroDireccion.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jlNumeroDireccion.setForeground(new java.awt.Color(0, 0, 255));
        jlNumeroDireccion.setText("N°");

        TxtN_direccion.setBackground(new java.awt.Color(204, 204, 255));
        TxtN_direccion.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                TxtN_direccionActionPerformed(evt);
            }
        });
        TxtN_direccion.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtN_direccionKeyTyped(evt);
            }
        });

        jlCiudad.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jlCiudad.setForeground(new java.awt.Color(0, 0, 255));
        jlCiudad.setText("Ciudad");

        txtp_nombre.setBackground(new java.awt.Color(204, 204, 255));
        txtp_nombre.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtp_nombreKeyTyped(evt);
            }
        });

        TxtCiudad.setBackground(new java.awt.Color(204, 204, 255));
        TxtCiudad.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtCiudadKeyTyped(evt);
            }
        });

        jlNombre.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jlNombre.setForeground(new java.awt.Color(0, 0, 255));
        jlNombre.setText("Nombres ");

        jlComuna.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jlComuna.setForeground(new java.awt.Color(0, 0, 255));
        jlComuna.setText("Comuna");

        jlApellido.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jlApellido.setForeground(new java.awt.Color(0, 0, 255));
        jlApellido.setText("Apellidos");

        txtCelular.setBackground(new java.awt.Color(204, 204, 255));
        txtCelular.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtCelularKeyTyped(evt);
            }
        });

        txtp_apellido.setBackground(new java.awt.Color(204, 204, 255));
        txtp_apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtp_apellidoKeyTyped(evt);
            }
        });

        txts_apellido.setBackground(new java.awt.Color(204, 204, 255));
        txts_apellido.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txts_apellidoKeyTyped(evt);
            }
        });

        jlRun.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jlRun.setForeground(new java.awt.Color(0, 0, 255));
        jlRun.setText("Run");

        txtRun.setBackground(new java.awt.Color(204, 204, 255));
        txtRun.setCursor(new java.awt.Cursor(java.awt.Cursor.TEXT_CURSOR));
        txtRun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtRunKeyTyped(evt);
            }
        });

        btnBuscarRun.setText("Buscar ");
        btnBuscarRun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarRunActionPerformed(evt);
            }
        });

        TxtDvrun.setBackground(new java.awt.Color(204, 204, 255));
        TxtDvrun.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                TxtDvrunKeyTyped(evt);
            }
        });

        btnLimpiar.setText("Limpiar");
        btnLimpiar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimpiarActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel3.setText("-");

        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_apoderadoLayout = new javax.swing.GroupLayout(panel_apoderado);
        panel_apoderado.setLayout(panel_apoderadoLayout);
        panel_apoderadoLayout.setHorizontalGroup(
            panel_apoderadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_apoderadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_apoderadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_apoderadoLayout.createSequentialGroup()
                        .addComponent(jlApellido)
                        .addGap(18, 18, 18)
                        .addComponent(txtp_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 144, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txts_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_apoderadoLayout.createSequentialGroup()
                        .addGroup(panel_apoderadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_apoderadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(panel_apoderadoLayout.createSequentialGroup()
                                    .addComponent(jlDireccion)
                                    .addGap(18, 18, 18)
                                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(18, 18, 18)
                                    .addComponent(jlNumeroDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addGroup(panel_apoderadoLayout.createSequentialGroup()
                                    .addGap(283, 283, 283)
                                    .addComponent(TxtN_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(panel_apoderadoLayout.createSequentialGroup()
                                .addComponent(jlContrasena)
                                .addGap(16, 16, 16)
                                .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(panel_apoderadoLayout.createSequentialGroup()
                        .addGroup(panel_apoderadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(panel_apoderadoLayout.createSequentialGroup()
                                .addGap(394, 394, 394)
                                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_apoderadoLayout.createSequentialGroup()
                                .addComponent(jlRun, javax.swing.GroupLayout.PREFERRED_SIZE, 36, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(txtRun, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtDvrun, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(49, 49, 49)
                                .addComponent(btnBuscarRun, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_apoderadoLayout.createSequentialGroup()
                                .addComponent(jlNombre)
                                .addGap(18, 18, 18)
                                .addComponent(txtp_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_apoderadoLayout.createSequentialGroup()
                                .addComponent(jlCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_apoderadoLayout.createSequentialGroup()
                                .addComponent(jlemail)
                                .addGap(18, 18, 18)
                                .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, 170, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(panel_apoderadoLayout.createSequentialGroup()
                                .addComponent(jlComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(TxtComuna, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(panel_apoderadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(panel_apoderadoLayout.createSequentialGroup()
                                        .addComponent(jlCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(107, 107, 107))
                                    .addComponent(TxtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(0, 156, Short.MAX_VALUE)))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        panel_apoderadoLayout.setVerticalGroup(
            panel_apoderadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_apoderadoLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_apoderadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlRun)
                    .addComponent(txtRun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(TxtDvrun, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(btnBuscarRun, javax.swing.GroupLayout.PREFERRED_SIZE, 31, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_apoderadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlNombre)
                    .addComponent(txtp_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(4, 4, 4)
                .addGroup(panel_apoderadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlApellido)
                    .addComponent(txtp_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txts_apellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(panel_apoderadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_apoderadoLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(panel_apoderadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jlContrasena)
                            .addComponent(txtContra, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(20, 20, 20)
                        .addGroup(panel_apoderadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlDireccion)
                            .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNumeroDireccion)
                            .addComponent(TxtN_direccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(panel_apoderadoLayout.createSequentialGroup()
                        .addGap(26, 26, 26)
                        .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(panel_apoderadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(TxtComuna, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlCiudad)
                    .addComponent(TxtCiudad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlComuna))
                .addGap(26, 26, 26)
                .addGroup(panel_apoderadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlemail)
                    .addComponent(txtemail, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panel_apoderadoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlCelular)
                    .addComponent(txtCelular, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(btnLimpiar, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panel_apoderado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(52, 52, 52)
                .addComponent(lblfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 405, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(panel_apoderado, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblfoto, javax.swing.GroupLayout.PREFERRED_SIZE, 275, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtnomimagenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnomimagenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnomimagenActionPerformed

    private void btnseleccionarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnseleccionarActionPerformed
        JFileChooser archivo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Formatos de Archivos JPEG(*.JPG;*.JPEG)", "jpg","jpeg");
        archivo.addChoosableFileFilter(filtro);
        archivo.setDialogTitle("Abrir Archivo");
        File ruta = new File("C:\\Users\\aleja\\Pictures");
        archivo.setCurrentDirectory(ruta);
        int ventana = archivo.showOpenDialog(null);
        if(ventana == JFileChooser.APPROVE_OPTION)
        {
            //Obtenemos la ruta de nuestra imagen seleccionada
            File file = archivo.getSelectedFile();
            //Lo imprimimos en una caja de texto para ver su ruta
            txtnomimagen.setText(String.valueOf(file));
            //de cierto modo necesitamos tener la imagen para ello debemos conocer la ruta de dicha imagen
            Image foto= getToolkit().getImage(txtnomimagen.getText());
            //Le damos dimension a nuestro label que tendra la imagen
            foto= foto.getScaledInstance(400, 185, Image.SCALE_DEFAULT);
            //Imprimimos la imagen en el label
            lblfoto.setIcon(new ImageIcon(foto));
        }
    }//GEN-LAST:event_btnseleccionarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        String finiquito = txtnomimagen.getText();
        String afp = txAfp.getText();
        String afp2 = txtAFP2.getText();
        String rut = this.txtRun.getText();

        CertificadosDAO cerDAO= new CertificadosDAO();

        //================================================
        Apoderado apo = new Apoderado();
        
        try {
            
            apo.setCelular(Integer.parseInt(this.txtCelular.getText()));
            apo.setN_direccion(Integer.parseInt(this.TxtN_direccion.getText()));
            
        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null,"Error En ingreso de registros Numericos");
            
        }
            
        try {
            int tipo_usuario = 1;
            apo.setRut(this.txtRun.getText());
            apo.setDvRut(this.TxtDvrun.getText());
            apo.setContra(this.txtContra.getText().toLowerCase());
            apo.setNombre(this.txtp_nombre.getText());
            apo.setP_apellido(this.txtp_apellido.getText());
            apo.setS_apelledio(this.txts_apellido.getText());            
            apo.setEmail(this.txtemail.getText());
            apo.setDireccion(this.txtDireccion.getText());
            apo.setTipo_usuario(tipo_usuario);           
            apo.setComuna(this.TxtComuna.getText());
            apo.setCiudad(this.TxtCiudad.getText());

        }catch(ExceptionInInitializerError ex){
            Logger.getLogger(pnlApoderado.class.getName()).log(Level.SEVERE, null, ex);
        }

        ApoderadoDAO apoDAO = new ApoderadoDAO();
        try {
            if(apoDAO.buscarApoderado(this.txtRun.getText())==null)
            {
                if(apoDAO.ingresarCuenta(apo)==true && cerDAO.ingresarSituacion(finiquito,afp,afp2, rut)==true  )
                {
                    JOptionPane.showMessageDialog(this,"Apoderado ingresada");
                    System.out.println("Apoderado ingresada");

                    //if (cerDAO.ingresarSituacion(finiquito,afp,afp2, rut)==true) {
                        JOptionPane.showMessageDialog(this,"situacion economica ingresada");
                        System.out.println("situacion economica ingresada");
                        // }
                    // else
                    // {
                        //     JOptionPane.showMessageDialog(this,"Hubo problemas....");
                        //    System.out.println("Hubo problemas....");
                        // }
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Hubo problemas....");
                    System.out.println("Hubo problemas....");
                }
            }
            else
            {
                JOptionPane.showMessageDialog(this, "Apoderado existente");
            }

        } catch (HeadlessException | FileNotFoundException | ClassNotFoundException e) {
            Logger.getLogger(pnlApoderado.class.getName()).log(Level.SEVERE, null, e);
        }

    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnSelectAfpActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectAfpActionPerformed
        JFileChooser archivo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Formatos de Archivos JPEG(*.JPG;*.JPEG)", "jpg","jpeg");
        archivo.addChoosableFileFilter(filtro);
        archivo.setDialogTitle("Abrir Archivo");
        File ruta = new File("C:\\Users\\aleja\\Pictures");
        archivo.setCurrentDirectory(ruta);
        int ventana = archivo.showOpenDialog(null);
        if(ventana == JFileChooser.APPROVE_OPTION)
        {
            //Obtenemos la ruta de nuestra imagen seleccionada
            File file = archivo.getSelectedFile();
            //Lo imprimimos en una caja de texto para ver su ruta
            txAfp.setText(String.valueOf(file));
            //de cierto modo necesitamos tener la imagen para ello debemos conocer la ruta de dicha imagen
            Image foto= getToolkit().getImage(txAfp.getText());
            //Le damos dimension a nuestro label que tendra la imagen
            foto= foto.getScaledInstance(400, 185, Image.SCALE_DEFAULT);
            //Imprimimos la imagen en el label
            lblfoto.setIcon(new ImageIcon(foto));
        }
    }//GEN-LAST:event_btnSelectAfpActionPerformed

    private void btnSelectAfp2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSelectAfp2ActionPerformed
        JFileChooser archivo = new JFileChooser();
        FileNameExtensionFilter filtro = new FileNameExtensionFilter("Formatos de Archivos JPEG(*.JPG;*.JPEG)", "jpg","jpeg");
        archivo.addChoosableFileFilter(filtro);
        archivo.setDialogTitle("Abrir Archivo");
        File ruta = new File("C:\\Users\\aleja\\Pictures");
        archivo.setCurrentDirectory(ruta);
        int ventana = archivo.showOpenDialog(null);
        if(ventana == JFileChooser.APPROVE_OPTION)
        {
            //Obtenemos la ruta de nuestra imagen seleccionada
            File file = archivo.getSelectedFile();
            //Lo imprimimos en una caja de texto para ver su ruta
            txtAFP2.setText(String.valueOf(file));
            //de cierto modo necesitamos tener la imagen para ello debemos conocer la ruta de dicha imagen
            Image foto= getToolkit().getImage(txtAFP2.getText());
            //Le damos dimension a nuestro label que tendra la imagen
            foto= foto.getScaledInstance(400, 185, Image.SCALE_DEFAULT);
            //Imprimimos la imagen en el label
            lblfoto.setIcon(new ImageIcon(foto));
        }
    }//GEN-LAST:event_btnSelectAfp2ActionPerformed

    private void txtDireccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtDireccionKeyTyped
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionKeyTyped

    private void TxtComunaKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtComunaKeyTyped
        char C= evt.getKeyChar();

        if(Character.isDigit(C))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo letras ");
            TxtComuna.setCursor(null);
        }
        else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
            ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
            || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
            || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo letras..sin espacio");
            TxtComuna.setCursor(null);
        }
    }//GEN-LAST:event_TxtComunaKeyTyped

    private void TxtN_direccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtN_direccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtN_direccionActionPerformed

    private void TxtN_direccionKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtN_direccionKeyTyped
        char C= evt.getKeyChar();

        if(Character.isDigit(C)&&Character.isLetter(C))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo Numeros ");
            TxtN_direccion.setCursor(null);
        }
        else if((int)evt.getKeyChar()>=32 && (int)evt.getKeyChar()<=47
            ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
            || (int)evt.getKeyChar()>=65 && (int)evt.getKeyChar()<=96
            || (int)evt.getKeyChar()>=97 && (int)evt.getKeyChar()<=255)
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo Numeros..sin espacio");
            TxtN_direccion.setCursor(null);
        }
    }//GEN-LAST:event_TxtN_direccionKeyTyped

    private void txtp_nombreKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtp_nombreKeyTyped
        char C= evt.getKeyChar();

        if(Character.isDigit(C))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo letras ");
            txtp_nombre.setCursor(null);
        }
        else if((int)evt.getKeyChar()>=32 && (int)evt.getKeyChar()<=47
            ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
            || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
            || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo letras..sin espacio");
            txtp_nombre.setCursor(null);
        }
    }//GEN-LAST:event_txtp_nombreKeyTyped

    private void TxtCiudadKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtCiudadKeyTyped
        char C= evt.getKeyChar();

        if(Character.isDigit(C))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo letras ");
            txtp_nombre.setCursor(null);
        }
        else if((int)evt.getKeyChar()>32 && (int)evt.getKeyChar()<=47
            ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
            || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
            || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo letras..sin espacio");
            txtp_nombre.setCursor(null);
        }
    }//GEN-LAST:event_TxtCiudadKeyTyped

    private void txtCelularKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtCelularKeyTyped
        char C= evt.getKeyChar();

        if(Character.isDigit(C)&&Character.isLetter(C))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo Numeros ");
            txtRun.setCursor(null);
        }
        else if((int)evt.getKeyChar()>=32 && (int)evt.getKeyChar()<=47
            ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
            || (int)evt.getKeyChar()>=65 && (int)evt.getKeyChar()<=96
            || (int)evt.getKeyChar()>=97 && (int)evt.getKeyChar()<=255)
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo Numeros..sin espacio");
            txtRun.setCursor(null);
        }
    }//GEN-LAST:event_txtCelularKeyTyped

    private void txtp_apellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtp_apellidoKeyTyped
        char C= evt.getKeyChar();

        if(Character.isDigit(C))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo letras ni espacio");
            txtp_apellido.setCursor(null);
        }
        else if((int)evt.getKeyChar()>=32 && (int)evt.getKeyChar()<=47
            ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
            || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
            || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo letras");
            txtp_apellido.setCursor(null);
        }
    }//GEN-LAST:event_txtp_apellidoKeyTyped

    private void txts_apellidoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txts_apellidoKeyTyped
        char C= evt.getKeyChar();

        if(Character.isDigit(C))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo letras ni espacio");
            txts_apellido.setCursor(null);
        }
        else if((int)evt.getKeyChar()>=32 && (int)evt.getKeyChar()<=47
            ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
            || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
            || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo letras");
            txts_apellido.setCursor(null);
        }
    }//GEN-LAST:event_txts_apellidoKeyTyped

    private void txtRunKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtRunKeyTyped
        char C= evt.getKeyChar();

        if(Character.isDigit(C)&&Character.isLetter(C))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo Numeros ");
            txtRun.setCursor(null);
        }
        else if((int)evt.getKeyChar()>=32 && (int)evt.getKeyChar()<=47
            ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
            || (int)evt.getKeyChar()>=65 && (int)evt.getKeyChar()<=96
            || (int)evt.getKeyChar()>=97 && (int)evt.getKeyChar()<=255)
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo Numeros..sin espacio");
            txtRun.setCursor(null);
        }
    }//GEN-LAST:event_txtRunKeyTyped

    private void btnBuscarRunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarRunActionPerformed
        String run =txtRun.getText();

        ApoderadoDAO apoDao= new ApoderadoDAO();
        Apoderado apo = apoDao.buscarApoderado(run);

        if (apo==null) {
            JOptionPane.showMessageDialog(this,"Rut no existe");
        }
        else{
            txtRun.setEditable(false);
            TxtDvrun.setText(apo.getDvRut());
            TxtDvrun.setEditable(false);
            txtContra.setText(apo.getContra());
            txtp_nombre.setText(apo.getNombre());
            txtp_apellido.setText(apo.getP_apellido());
            txts_apellido.setText(apo.getS_apelledio());
            txtCelular.setText(String.valueOf(apo.getCelular()));
            txtemail.setText(apo.getEmail());
            txtDireccion.setText(apo.getDireccion());
            TxtN_direccion.setText(String.valueOf(apo.getN_direccion()));
            TxtComuna.setText(apo.getComuna());
            TxtCiudad.setText(apo.getCiudad());
        }
    }//GEN-LAST:event_btnBuscarRunActionPerformed

    private void TxtDvrunKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_TxtDvrunKeyTyped
        char C= evt.getKeyChar();

        if(Character.isDigit(C)&&Character.isLetter(C))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo letras ni espacio");
            TxtDvrun.setCursor(null);
        }
        else if((int)evt.getKeyChar()>=32 && (int)evt.getKeyChar()<=47
            ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=74
            ||(int)evt.getKeyChar()>=76 && (int)evt.getKeyChar()<=106
            ||(int)evt.getKeyChar()>=108 && (int)evt.getKeyChar()<=255

        )
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo numeros o 'K'");

        }
    }//GEN-LAST:event_TxtDvrunKeyTyped

    private void btnLimpiarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimpiarActionPerformed
        txtRun.setText(null);
        txtRun.setEditable(true);
        TxtDvrun.setText(null);
        TxtDvrun.setEditable(true);
        txtContra.setText(null);
        txtp_nombre.setText(null);
        txtp_apellido.setText(null);
        txts_apellido.setText(null);
        txtCelular.setText(null);
        txtemail.setText(null);
        txtDireccion.setText(null);
        TxtN_direccion.setText(null);
        TxtComuna.setText(null);
        TxtCiudad.setText(null);
    }//GEN-LAST:event_btnLimpiarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        String rut,dv_rut,usuario,contrasena,nombre,p_apellido,s_apellido,email,direccion,comuna,ciudad;
        int celular,n_direccion,telefono;
        int tipo_usuario = 1;

        rut=txtRun.getText();
        dv_rut=this.TxtDvrun.getText();
        contrasena=this.txtContra.getText();
        nombre=this.txtp_nombre.getText();
        p_apellido=this.txtp_apellido.getText();
        s_apellido=this.txts_apellido.getText();
        celular=Integer.parseInt(this.txtCelular.getText());
        email=this.txtemail.getText();
        direccion=this.txtDireccion.getText();
        n_direccion=Integer.parseInt(this.TxtN_direccion.getText());
        comuna=this.TxtComuna.getText();
        ciudad=this.TxtCiudad.getText();

        Apoderado apo = new Apoderado(rut, dv_rut, contrasena, nombre, p_apellido, s_apellido, celular, email, direccion, tipo_usuario, n_direccion, comuna, ciudad);

        ApoderadoDAO apoDao = new ApoderadoDAO();

        if (apoDao.ModificarApoderado(apo)) {
            JOptionPane.showMessageDialog(this, "Se modifico");
        }
        else
        JOptionPane.showMessageDialog(this, "No se modifico");

    }//GEN-LAST:event_btnModificarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int valor=JOptionPane.showConfirmDialog(this, "Quiere Eliminar Datos","Advertencia",JOptionPane.YES_NO_OPTION);
        if(valor==JOptionPane.YES_OPTION){

            String run= txtRun.getText();
            ApoderadoDAO apoDao=new ApoderadoDAO();

            if(apoDao.eliminarApoderado(run))
            {
                JOptionPane.showMessageDialog(this, "Datos Del Apoderado Eliminado");
            }
            else
            JOptionPane.showMessageDialog(this, "Datos Del Apoderado NO Eliminado");
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void txtDireccionActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDireccionActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDireccionActionPerformed

    private void TxtComunaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_TxtComunaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_TxtComunaActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField TxtCiudad;
    private javax.swing.JTextField TxtComuna;
    private javax.swing.JTextField TxtDvrun;
    private javax.swing.JTextField TxtN_direccion;
    private javax.swing.JButton btnBuscarRun;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnLimpiar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JButton btnSelectAfp;
    private javax.swing.JButton btnSelectAfp2;
    private javax.swing.JButton btnseleccionar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel jlApellido;
    private javax.swing.JLabel jlCelular;
    private javax.swing.JLabel jlCiudad;
    private javax.swing.JLabel jlComuna;
    private javax.swing.JLabel jlContrasena;
    private javax.swing.JLabel jlDireccion;
    private javax.swing.JLabel jlNombre;
    private javax.swing.JLabel jlNumeroDireccion;
    private javax.swing.JLabel jlRun;
    private javax.swing.JLabel jlemail;
    private javax.swing.JLabel lblfoto;
    private javax.swing.JPanel panel_apoderado;
    private javax.swing.JTextField txAfp;
    private javax.swing.JTextField txtAFP2;
    private javax.swing.JTextField txtCelular;
    private javax.swing.JTextField txtContra;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtRun;
    private javax.swing.JTextField txtemail;
    private javax.swing.JTextField txtnomimagen;
    private javax.swing.JTextField txtp_apellido;
    private javax.swing.JTextField txtp_nombre;
    private javax.swing.JTextField txts_apellido;
    // End of variables declaration//GEN-END:variables
}
