/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package vista.panel;

import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import modelo.ControlEmail;
import modelo.Correo;
import modelo.Orden;
import modelo.OrdenDAO;
import modelo.Profesional;
import modelo.ProfesionalDAO;
import modelo.Proveedor;
import modelo.ProveedorDAO;

public class pnlGeneralOrden extends javax.swing.JPanel {

    /**
     * Creates new form pnlGeneralOrden
     */
    public pnlGeneralOrden() {
        initComponents();
         txtId_Orden.setText(uuid());
        cargarNomProov();
        cargarNomProf();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jP_orden = new javax.swing.JPanel();
        jlIdentificador = new javax.swing.JLabel();
        txtId_Orden = new javax.swing.JTextField();
        txtNombre_producto = new javax.swing.JTextField();
        jlDescripcion = new javax.swing.JLabel();
        jlNom_prod = new javax.swing.JLabel();
        txtStock = new javax.swing.JTextField();
        jlStock = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        txtDescripcion = new javax.swing.JTextArea();
        jlProveedor = new javax.swing.JLabel();
        cmbProveedor_name = new javax.swing.JComboBox<>();
        jlProfseional = new javax.swing.JLabel();
        cmbProfesional_nombre = new javax.swing.JComboBox<>();
        btnBuscar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();

        setBackground(new java.awt.Color(255, 255, 255));

        jP_orden.setBackground(new java.awt.Color(255, 255, 255));
        jP_orden.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createTitledBorder("Generar Orden")));

        jlIdentificador.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jlIdentificador.setForeground(new java.awt.Color(0, 0, 255));
        jlIdentificador.setText("Identificador ");

        txtId_Orden.setBackground(new java.awt.Color(204, 204, 255));
        txtId_Orden.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtId_OrdenActionPerformed(evt);
            }
        });
        txtId_Orden.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtId_OrdenKeyTyped(evt);
            }
        });

        txtNombre_producto.setBackground(new java.awt.Color(204, 204, 255));
        txtNombre_producto.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtNombre_productoKeyTyped(evt);
            }
        });

        jlDescripcion.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jlDescripcion.setForeground(new java.awt.Color(0, 0, 255));
        jlDescripcion.setText("Descripcion");

        jlNom_prod.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jlNom_prod.setForeground(new java.awt.Color(0, 0, 255));
        jlNom_prod.setText("Nombre Producto");

        txtStock.setBackground(new java.awt.Color(204, 204, 255));
        txtStock.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyTyped(java.awt.event.KeyEvent evt) {
                txtStockKeyTyped(evt);
            }
        });

        jlStock.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jlStock.setForeground(new java.awt.Color(0, 0, 255));
        jlStock.setText("Stock");

        txtDescripcion.setBackground(new java.awt.Color(204, 204, 255));
        txtDescripcion.setColumns(20);
        txtDescripcion.setRows(5);
        jScrollPane1.setViewportView(txtDescripcion);

        jlProveedor.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jlProveedor.setForeground(new java.awt.Color(0, 0, 255));
        jlProveedor.setText("Proveedor");

        cmbProveedor_name.setBackground(new java.awt.Color(204, 204, 255));

        jlProfseional.setFont(new java.awt.Font("Arial", 1, 11)); // NOI18N
        jlProfseional.setForeground(new java.awt.Color(0, 0, 255));
        jlProfseional.setText("Profesional");

        cmbProfesional_nombre.setBackground(new java.awt.Color(204, 204, 255));

        btnBuscar.setText("Buscar");
        btnBuscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBuscarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jP_ordenLayout = new javax.swing.GroupLayout(jP_orden);
        jP_orden.setLayout(jP_ordenLayout);
        jP_ordenLayout.setHorizontalGroup(
            jP_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ordenLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addGroup(jP_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_ordenLayout.createSequentialGroup()
                        .addComponent(jlStock, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP_ordenLayout.createSequentialGroup()
                        .addComponent(jlDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 273, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP_ordenLayout.createSequentialGroup()
                        .addComponent(jlIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 74, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtId_Orden, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP_ordenLayout.createSequentialGroup()
                        .addComponent(jlProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbProveedor_name, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP_ordenLayout.createSequentialGroup()
                        .addComponent(jlNom_prod, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtNombre_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jP_ordenLayout.createSequentialGroup()
                        .addComponent(jlProfseional, javax.swing.GroupLayout.PREFERRED_SIZE, 96, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(cmbProfesional_nombre, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 73, Short.MAX_VALUE)
                .addGroup(jP_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 137, Short.MAX_VALUE))
                .addContainerGap())
        );
        jP_ordenLayout.setVerticalGroup(
            jP_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jP_ordenLayout.createSequentialGroup()
                .addGroup(jP_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jP_ordenLayout.createSequentialGroup()
                        .addGap(36, 36, 36)
                        .addGroup(jP_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jlIdentificador, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtId_Orden, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 25, Short.MAX_VALUE)
                        .addGroup(jP_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNombre_producto, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jlNom_prod, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jP_ordenLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)))
                .addGroup(jP_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtStock, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jlStock, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnBuscar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(9, 9, 9)
                .addGroup(jP_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jlProveedor, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmbProveedor_name))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jP_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jP_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jlProfseional, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(cmbProfesional_nombre, javax.swing.GroupLayout.DEFAULT_SIZE, 22, Short.MAX_VALUE))
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 46, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(jP_ordenLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jlDescripcion, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 665, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jP_orden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 447, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(jP_orden, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtId_OrdenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtId_OrdenActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtId_OrdenActionPerformed

    private void txtId_OrdenKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtId_OrdenKeyTyped

    }//GEN-LAST:event_txtId_OrdenKeyTyped

    private void txtNombre_productoKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNombre_productoKeyTyped
        char C= evt.getKeyChar();

        if(Character.isDigit(C))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo letras ");
            txtNombre_producto.setCursor(null);
        }
        else if((int)evt.getKeyChar()>=33 && (int)evt.getKeyChar()<=47
            ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
            || (int)evt.getKeyChar()>=91 && (int)evt.getKeyChar()<=96
            || (int)evt.getKeyChar()>=123 && (int)evt.getKeyChar()<=255)
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo letras");
            txtNombre_producto.setCursor(null);
        }
    }//GEN-LAST:event_txtNombre_productoKeyTyped

    private void txtStockKeyTyped(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtStockKeyTyped
        char C= evt.getKeyChar();

        if(Character.isDigit(C)&&Character.isLetter(C))
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo Numeros ");
            txtStock.setCursor(null);
        }
        else if((int)evt.getKeyChar()>=32 && (int)evt.getKeyChar()<=47
            ||(int)evt.getKeyChar()>=58 && (int)evt.getKeyChar()<=64
            || (int)evt.getKeyChar()>=65 && (int)evt.getKeyChar()<=96
            || (int)evt.getKeyChar()>=97 && (int)evt.getKeyChar()<=255)
        {
            getToolkit().beep();
            evt.consume();
            JOptionPane.showMessageDialog(this, "Ingrese solo letras..sin espacio");
            txtStock.setCursor(null);
        }
    }//GEN-LAST:event_txtStockKeyTyped

    private void btnBuscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBuscarActionPerformed
        String id_orden =txtId_Orden.getText();

        OrdenDAO ordDAO=new OrdenDAO();
        Orden ord = ordDAO.buscarOrden(id_orden);

        if (ord==null) {
            JOptionPane.showMessageDialog(this,"Orden no existe");
        }
        else{
            txtId_Orden.setEditable(false);
            txtDescripcion.setText(ord.getDescripcion());
            txtNombre_producto.setText(ord.getNom_product());
            txtStock.setText(String.valueOf(ord.getStock()));
            cmbProveedor_name.setSelectedItem(ord.getRut_proveedor());
            cmbProfesional_nombre.setSelectedItem(ord.getRut_profesional());
        }
    }//GEN-LAST:event_btnBuscarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        int valor=JOptionPane.showConfirmDialog(this, "Quiere Eliminar Orden","Advertencia",JOptionPane.YES_NO_OPTION);
        if(valor==JOptionPane.YES_OPTION){

            String id_codigo= this.txtId_Orden.getText();
            OrdenDAO ordDao=new OrdenDAO();
            String Asunto="Solicitud de Eliminacion de Orden N°"+id_codigo;
            String DetalleODC="Cancelacion de la Orden de compra N°"+id_codigo+".\n";
            String id_orden =txtId_Orden.getText();

            OrdenDAO ordDAO=new OrdenDAO();
            Orden ord = ordDAO.buscarOrden(id_orden);

            if (ord==null) {
                JOptionPane.showMessageDialog(this,"Orden no existe");
            }
            else{

                String descripcion=ord.getDescripcion();
                String nom_prodt=ord.getNom_product();
                int stock=ord.getStock();
                String proveedor=ord.getRut_proveedor();
                String profesional=ord.getRut_profesional();

                ProveedorDAO provDAO=new ProveedorDAO();
                Proveedor prov = provDAO.buscarNomProv(proveedor);
                if (prov==null) {
                    JOptionPane.showMessageDialog(this,"Email del Proveedor no encontrado");
                }
                else
                {

                    String email_prov=prov.getEmail();
                    enviarCorreo(stock, nom_prodt, profesional, email_prov,Asunto,DetalleODC);
                    if(ordDao.eliminarOrden(id_codigo))
                    {
                        JOptionPane.showMessageDialog(this, "Orden Eliminada");
                    }
                    else
                    JOptionPane.showMessageDialog(this, "Orden NO Eliminada");
                }
            }
        }
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        Orden ord = new Orden();
            String nom_proveedor="",nom_profesional="",nom_prod="", id_orden="", asunto="",DetalleODC="";
            int stock = 0;

        try{
             nom_proveedor=cmbProveedor_name.getSelectedItem().toString();
             nom_profesional=cmbProfesional_nombre.getSelectedItem().toString();
             nom_prod=this.txtNombre_producto.getText();
             id_orden=this.txtId_Orden.getText();
             asunto="Orden de Compra N°"+id_orden;
             DetalleODC="Compra";
            
            ord.setId_orden(id_orden);
            ord.setDescripcion(this.txtDescripcion.getText());
            ord.setNom_product(nom_prod);
        }catch(ExceptionInInitializerError ex){
            Logger.getLogger(pnlApoderado.class.getName()).log(Level.SEVERE, null, ex);
        }
        try 
        {
            stock = Integer.parseInt(this.txtStock.getText());

            ord.setStock(stock);            

        } catch (NumberFormatException nfe) {
            JOptionPane.showMessageDialog(null,"Error En ingreso de registros Numericos");
        }

        OrdenDAO ordDAO = new OrdenDAO();
        try {
            ProveedorDAO provDAO=new ProveedorDAO();
            Proveedor prov = provDAO.buscarNomProv(nom_proveedor);
            if (prov==null) {
                JOptionPane.showMessageDialog(this,"Email del Proveedor no encontrado");
            }
            else
            {
                

                if(ordDAO.ingresarOrden(ord,nom_proveedor,nom_profesional))
                {
                    JOptionPane.showMessageDialog(this,"Orden ingresada");
                    System.out.println("Servicio ingresado");
                    
                    String email_prov=prov.getEmail();
                    enviarCorreo(stock, nom_prod, nom_profesional, email_prov,asunto,DetalleODC);
                }
                else{
                    JOptionPane.showMessageDialog(this,"Hubo problemas....");
                    System.out.println("Hubo problemas....");
                }
            }
        } catch (Exception e) {
            Logger.getLogger(pnlGeneralOrden.class.getName()).log(Level.SEVERE, null, e);
        }
    }//GEN-LAST:event_btnRegistrarActionPerformed
 public static final String uuid()
    {
        String result = java.util.UUID.randomUUID().toString();

        result=result.replaceAll("-", "");
        result=result.substring(0, 8);

        return result;
    }
   
    public void cargarNomProov(){
         
        ProveedorDAO provDao=new ProveedorDAO();
        
        ArrayList<Proveedor>proov=provDao.buscarNomProov();
        
         if (proov==null) {
              cmbProveedor_name.addItem("Error en Base de datos"); 
         }
         else{
             for (int i = 0; i < proov.size(); i++) {
                   
                    String p_nombre=proov.get(i).getNombre(); 
                    cmbProveedor_name.addItem(p_nombre); 
             }
         }

    }
    
    public void cargarNomProf(){
        ProfesionalDAO profDao=new ProfesionalDAO();
        
        ArrayList<Profesional>prof=profDao.buscarNomProf();

            for (int i = 0; i < prof.size(); i++) {

                    String p_nombre=prof.get(i).getNombre();                  
                    String p_apellido=prof.get(i).getP_apellido();  
                    String s_apellido=prof.get(i).getS_apellido();  
                    
                    String fullname=p_nombre+" "+p_apellido+" "+s_apellido;
                    
                    cmbProfesional_nombre.addItem(fullname); 
    
         }    
        
    }
     Correo c = new Correo();
    public void enviarCorreo(int stock, String nom_producto,String nom_prof,String email,String asunto,String DetalleODC){
        
        c.setContrasenia("wgdluzzjvmvtzohy");
        c.setUsuarioCorreo("lindasonrisaodontologia@gmail.com");
        c.setAsunto(asunto);
        c.setMensaje("Estimado.\nSe Necesita Realizar la "+DetalleODC+" de "+stock+" unidades de "+nom_producto+". \n\nSaludos Cordiales\nAtte "+nom_prof);
        c.setDestino(email.trim());
        c.setNombreArchivo("imagen.jpg");
        c.setRutArchivo("src\\img\\logo.jpg");
        ControlEmail co = new ControlEmail();
        if (co.enviarCorreo(c)) {
            JOptionPane.showMessageDialog(null, "Envio Correo");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Error");
        }


    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBuscar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JComboBox<String> cmbProfesional_nombre;
    private javax.swing.JComboBox<String> cmbProveedor_name;
    private javax.swing.JPanel jP_orden;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel jlDescripcion;
    private javax.swing.JLabel jlIdentificador;
    private javax.swing.JLabel jlNom_prod;
    private javax.swing.JLabel jlProfseional;
    private javax.swing.JLabel jlProveedor;
    private javax.swing.JLabel jlStock;
    private javax.swing.JTextArea txtDescripcion;
    private javax.swing.JTextField txtId_Orden;
    private javax.swing.JTextField txtNombre_producto;
    private javax.swing.JTextField txtStock;
    // End of variables declaration//GEN-END:variables

   
}
